# Generated by Django 4.2.19 on 2025-02-15 16:20

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornote',
            name='note_text',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
    ]
